### ISSUE TITLE
Results are too bad!

### ISSUE THREAD

**Issue by eslambakr** [Jyxarthur/flowsam#13]
Dears,

Thanks for sharing the source code of your work.

I have tried it on a random YouTube video, which is attached below.
Unfortunately, the results are too bad. Therefore, I wonder if I am doing something wrong or if the model does not generalize well.

Thanks in advance!

https://github.com/user-attachments/assets/828c3162-36ca-4314-8f53-c538633bd2da

https://github.com/user-attachments/assets/ff076265-5146-44ad-b8a3-a79dcac441a5

**Comment by Jyxarthur** [comment]
Hi,
Could you provide more details regarding the model and checkpoint used?
It appears that only three masks are segmented per frame. Could you please check if there are more than three masks outputs?
Besides, since there are many objects contained in the video, adjusting `--max_obj` to a higher number and using a denser grid (i.e. larger `--num_gridside`) would probably help.

**Comment by eslambakr** [comment]
Hi @Jyxarthur 

Thank you so much for your prompt response!
Yes, I set the maximum number of objects to 3 as I have only one moving object in this video.
But, regardless of the number of masks, the masks themselves are wrong.
As this is a moving object segmentation task, isn't it? 
Thus, the masks should represent moving objects; however, they segment static objects, as seen in the image below.

Below, you can find my configuration from the running command:
<img width="1033" alt="Screen Shot 2024-08-17 at 12 13 39 AM" src="https://github.com/user-attachments/assets/a8f79f76-b60e-4a6f-8e0a-a03a4b7b642c">

Sample of the output:
![00018](https://github.com/user-attachments/assets/a1479107-093a-4372-90b8-7783318b1857)

I'm looking forward to hearing back from you!
Thank you so much!

**Comment by Jyxarthur** [comment]
Thanks a lot for the clarification.

Since the FlowPSAM provides two scores (fIoU based on RGB input, and MOS based on flow input), it does not only focus on the moving objects but also on some foreground objects (with high fIoU scores).

Regarding the video shown, would you mind also providing the flow frames (e.g. gap 1) as an additional visualisation? This is because FlowPSAM predicts MOS scores (whether the object is moving) based on observing the flow field. 

From the RGB frames, there are several points that I noticed (which may be observed more clearly in the flow field):
1. The person only moves noticeably between 1s and 2s and is segmented during this period. Before 1s, she is standing (almost static) and far from the camera. As a result, the per-frame FlowPSAM may not predict a large MOS score for it, therefore it is not shown as one of the major three masks in the output image you provided. 
2. Since there is a large camera motion, it is suspected that the motion parallax would result in some observable flow field boundaries for the static objects (e.g. the table and the lamp), which makes the FlowPSAM treat them as "moving" to some extent.

To further improve the results, there are several alternative settings:
1. Try the other checkpoint trained on DAVIS17 (without "m")
2. The default FlowPSAM uses MOS + fIoU to filter the foreground moving object masks. To emphasize the "moving" object over the "foreground" objects, it would probably help to put a bit more weight on MOS (which can be directly implemented in the place shown below).
https://github.com/Jyxarthur/flowsam/blob/57c5c40c92c73fd3244631409610c4b2ec1d5097/evaluation.py#L37
3. In this particular video, since the person is not moving initially with a possibly low MOS score, it would still be useful to increase the number of predicted objects so that the person's mask would not be excluded.

**Comment by eslambakr** [comment]
Thanks a lot, @Jyxarthur, for your support and the suggestions.

Below is the output video for flow gap-1:

https://github.com/user-attachments/assets/a608c2b3-7510-479c-a5a8-e9a4dcc61e40

Then below is the output after using the checkpoint trained on DAVIS17 (without "m") and increasing the number of masks from 3 to 10. But unfortunately, as u can see, we have a lot of masks for static objects:

https://github.com/user-attachments/assets/7a03a7c3-31db-4656-850a-62ff4c182659

https://github.com/user-attachments/assets/2eb028b2-c59c-46c4-b9d7-df58866bb396

Then, I tried to adjust the score by giving a higher weight to the MOS, as advised. But the output still very bad and a lot of static objects are detected by mistake.

`score = 0.2*fiou + 0.8*mos`

https://github.com/user-attachments/assets/01beca80-7b67-4121-9e4c-0d6eb6656bc1

**Comment by Jyxarthur** [comment]
Thank you for the feedback.

Yes, as can be seen in the flow field, the motion parallax leads to observable flow boundaries for static objects. 
I am afraid that our current model determines whether the object is "moving" based on observing optical flow, without relying on the semantics (e.g., the chair should not move, the person can move, etc. --- which could be definitely a possible future direction). This setting naturally allows the depth-parallax objects to be recognized as "moving" (as they also show flow signals), and this broader definition of "moving" aligns with our motivation to use motion to define and discover foreground objects (similar to how an infant learns what is an object). 

The specific example you offered demonstrates a large camera motion (therefore large motion parallax) and a relatively small object motion. Essentially these two factors compete with each other, and the model would provide a higher moving object score for the object that appears to have a more obvious flow signal, resulting in a lot of depth-parallax foreground objects being segmented. 

To understand the detailed outputs, for the initial first second, the person is almost static (as shown by the flow signal), therefore it is not treated as the major moving object during the first second. For the later frames, the person starts to be segmented mostly into "red" and "green", meaning it is recognized as the most (or the second most) dominant "moving" object. 

Hopefully this would help to understand the results you observed.

**Comment by eslambakr** [comment]
Thank you so much!

Indeed, as you said, the current model can not handle the moving camera case well and suffers from generalization ability.

Adding semantics will also not be enough, as in some specific scenarios, the chair will be considered a moving object if a person is pushing it.

I hope to see a robust general model for moving object detection and segmentation soon.

Again, thank you so much for your efforts and the insightful discussion.
